#!/usr/bin/env bash
# instantiate.sh — copy-rename-publish helper for entity_token_template (ET-M3).
# Spec: milestone/entity_token_template/template_flow.md §7 + m3.md.
#
# Produces a deployable per-entity token package from the template by renaming
# the module and its one-time witness to the entity's slug, and substituting the
# editable metadata constants. It NEVER changes DECIMALS (fixed at 6 for USDC
# parity, T3/T4) — that is guarded and the script refuses to emit otherwise.
#
# Assumes GNU sed (Linux / WSL). On macOS, install and use `gsed` (or run under
# WSL); BSD sed's `-i` differs.
#
# Usage:
#   scripts/instantiate.sh <slug> [--out DIR] [--name STR] [--symbol STR] \
#                          [--description STR] [--icon URL] [--force]
#
#   <slug>  lowercase snake_case. Becomes the package name, the module name, and
#           (uppercased) the OTW struct name — the witness MUST equal the module
#           name uppercased or `create_currency`'s OTW check aborts. e.g.
#           maple_street_deed -> module maple_street_deed, witness
#           MAPLE_STREET_DEED.
#
# Example:
#   scripts/instantiate.sh maple_street_deed \
#     --name "Maple Street Housing Deed" --symbol MSHD \
#     --description "Fractional equity in the Maple Street build (asset 0x..)."
set -euo pipefail

die() { echo "error: $*" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: instantiate.sh <slug> [--out DIR] [--name STR] [--symbol STR] [--description STR] [--icon URL] [--force]"

SLUG="$1"; shift
OUT=""; NAME=""; SYMBOL=""; DESCRIPTION=""; ICON=""; FORCE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --out)         OUT="$2"; shift 2;;
    --name)        NAME="$2"; shift 2;;
    --symbol)      SYMBOL="$2"; shift 2;;
    --description) DESCRIPTION="$2"; shift 2;;
    --icon)        ICON="$2"; shift 2;;
    --force)       FORCE=1; shift;;
    --decimals)    die "decimals is fixed at 6 (USDC parity, T3/T4) and cannot be changed";;
    *)             die "unknown argument: $1";;
  esac
done

# slug: lowercase snake_case, starting with a letter.
[[ "$SLUG" =~ ^[a-z][a-z0-9_]*$ ]] \
  || die "slug must be lowercase snake_case matching ^[a-z][a-z0-9_]*\$ (got: '$SLUG')"

# Values must not break the b"..." substitution or the sed delimiter.
check_value() {
  case "$2" in
    *'"'*|*'|'*) die "value for $1 must not contain '\"' or '|'";;
  esac
}
check_value name "$NAME"
check_value symbol "$SYMBOL"
check_value description "$DESCRIPTION"
check_value icon "$ICON"

SLUG_UPPER="$(printf '%s' "$SLUG" | tr '[:lower:]' '[:upper:]')"
TEMPLATE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[ -f "$TEMPLATE_ROOT/sources/entity_token.move" ] \
  || die "template source not found under $TEMPLATE_ROOT"

OUT="${OUT:-$PWD/generated/$SLUG}"
if [ -e "$OUT" ]; then
  [ "$FORCE" -eq 1 ] || die "output dir already exists: $OUT (use --force to overwrite)"
  rm -rf "$OUT"
fi

mkdir -p "$OUT/sources" "$OUT/tests"
cp "$TEMPLATE_ROOT/Move.toml" "$OUT/Move.toml"
if [ -f "$TEMPLATE_ROOT/.gitignore" ]; then cp "$TEMPLATE_ROOT/.gitignore" "$OUT/.gitignore"; fi
cp "$TEMPLATE_ROOT/sources/entity_token.move" "$OUT/sources/${SLUG}.move"
cp "$TEMPLATE_ROOT/tests/entity_token_tests.move" "$OUT/tests/${SLUG}_tests.move"

SRC="$OUT/sources/${SLUG}.move"
TST="$OUT/tests/${SLUG}_tests.move"

# Structural rename. Order matters — longest identifiers first so substrings are
# not mangled (entity_token_template, then entity_token_tests, then entity_token,
# then the uppercase witness).
for f in "$OUT/Move.toml" "$SRC" "$TST"; do
  sed -i \
    -e "s/entity_token_template/${SLUG}/g" \
    -e "s/entity_token_tests/${SLUG}_tests/g" \
    -e "s/entity_token/${SLUG}/g" \
    -e "s/ENTITY_TOKEN/${SLUG_UPPER}/g" \
    "$f"
done

# Metadata constants — only overwrite the ones the operator supplied.
subst() { sed -i "s|const $1: vector<u8> = b\".*\";|const $1: vector<u8> = b\"$2\";|" "$SRC"; }
if [ -n "$NAME" ];        then subst NAME "$NAME"; fi
if [ -n "$SYMBOL" ];      then subst SYMBOL "$SYMBOL"; fi
if [ -n "$DESCRIPTION" ]; then subst DESCRIPTION "$DESCRIPTION"; fi
if [ -n "$ICON" ];        then subst ICON_URL "$ICON"; fi

# Guards.
grep -q 'const DECIMALS: u8 = 6;' "$SRC" \
  || die "DECIMALS is not 6 in the generated package — refusing to emit an off-spec token"
grep -q "module ${SLUG}::${SLUG};" "$SRC"            || die "module rename failed"
grep -q "public struct ${SLUG_UPPER} has drop {}" "$SRC" || die "witness rename failed"

# Provenance banner. The structural sed also rewrites the spec-path mention in the
# template's doc header, so this banner restores an accurate pointer to the
# canonical (unrenamed) spec.
BANNER="// Generated by entity_token_template/scripts/instantiate.sh — canonical spec: milestone/entity_token_template/template_flow.md. DECIMALS is fixed at 6; do not change."
{ echo "$BANNER"; cat "$SRC"; } > "$SRC.tmp" && mv "$SRC.tmp" "$SRC"

echo "✓ generated '$SLUG' at: $OUT"
echo "  package ${SLUG} · module ${SLUG}::${SLUG} · witness ${SLUG_UPPER} · decimals 6"
echo
echo "next:"
echo "  cd \"$OUT\""
echo "  sui move build      # expect 0 warnings"
echo "  sui client publish  # init freezes the metadata and sends you a virgin TreasuryCap"
echo "  # then finalize the raise — see entity_token_template/README.md"
