// AUTO-GENERATED by scripts/docs/gen.mjs — slim nav (no page HTML).
/* eslint-disable */
export interface DocNavLink { title: string; route: string; }
export interface DocNavGroup { part: string; pages: DocNavLink[]; }
export const DOCS_NAV: DocNavGroup[] = [
  {
    "part": "Understand",
    "pages": [
      {
        "title": "Introduction",
        "route": "/docs"
      },
      {
        "title": "Core Concepts",
        "route": "/docs/concepts"
      },
      {
        "title": "The Asset Lifecycle",
        "route": "/docs/lifecycle"
      },
      {
        "title": "The Economic Model",
        "route": "/docs/economics"
      },
      {
        "title": "Wrapping, Liquidity & Collateral",
        "route": "/docs/wrapping"
      },
      {
        "title": "Trust & Security Model",
        "route": "/docs/security"
      }
    ]
  },
  {
    "part": "Use",
    "pages": [
      {
        "title": "Getting Started",
        "route": "/docs/getting-started"
      },
      {
        "title": "Investor Guide",
        "route": "/docs/guides/investor"
      },
      {
        "title": "Challenger Guide",
        "route": "/docs/guides/challenger"
      },
      {
        "title": "Keeper & Maintenance (Cranks)",
        "route": "/docs/guides/keeper"
      },
      {
        "title": "Validators, Entities & Admin",
        "route": "/docs/roles"
      },
      {
        "title": "Reading the Explorer",
        "route": "/docs/explorer"
      },
      {
        "title": "Worked Examples",
        "route": "/docs/scenarios"
      }
    ]
  },
  {
    "part": "Build & Operate",
    "pages": [
      {
        "title": "System Architecture",
        "route": "/docs/architecture"
      },
      {
        "title": "Run & Build",
        "route": "/docs/run"
      }
    ]
  },
  {
    "part": "Reference",
    "pages": [
      {
        "title": "FAQ",
        "route": "/docs/faq"
      },
      {
        "title": "Glossary",
        "route": "/docs/glossary"
      },
      {
        "title": "Parameters Reference",
        "route": "/docs/parameters"
      }
    ]
  }
];
